be name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish

    permissions:
      contents: read
      id-token: write # For npm provenance

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public --provenance
        env:
          NPM_CONFIG_PROVENANCE: true

  publish-gpr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for GPR
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"

      - name: Configure package for GPR
        run: |
          cp package.json package.json.backup
          sed 's/"name": "@scxml\/parser"/"name": "@caweinshenker\/scxml-parser"/g' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to GPR
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore package.json
        run: mv package.json.backup package.json
